import type { DummyProduct } from "@/types"

export const dummyProducts = [
  {
    id: "1",
    name: "Pentax K1000",
    description:
      "The Pentax K1000 is a 35 mm single-lens reflex camera, launched in 1976 by Asahi Optical Co., Ltd.",
    image: "/images/pentax-k1000.jpg",
    brand: "Pentax",
    category: "Cameras",
    price: 249.99,
    countInStock: 8,
    rating: 4.6,
    numReviews: 12,
  },
  {
    id: "2",
    name: "Olympus OM-1",
    description:
      "The Olympus OM-1 is a single-lens reflex camera introduced in 1972.",
    image: "/images/olympus-om-1.jpg",
    brand: "Olympus",
    category: "Cameras",
    price: 299.99,
    countInStock: 6,
    rating: 4.7,
    numReviews: 10,
  },
  {
    id: "3",
    name: "Minolta X-700",
    description:
      "The Minolta X-700 is a 35 mm single-lens reflex film camera introduced by Minolta in 1981.",
    image: "/images/minolta-x700.jpg",
    brand: "Minolta",
    category: "Cameras",
    price: 279.99,
    countInStock: 5,
    rating: 4.5,
    numReviews: 8,
  },
  {
    id: "4",
    name: "Yashica Electro 35",
    description:
      "The Yashica Electro 35 is a rangefinder camera made by Yashica.",
    image: "/images/yashica-electro-35.jpg",
    brand: "Yashica",
    category: "Cameras",
    price: 199.99,
    countInStock: 7,
    rating: 4.4,
    numReviews: 9,
  },
  {
    id: "5",
    name: "Canon A-1",
    description:
      "The Canon A-1 is a 35 mm single-lens reflex camera that was introduced by Canon in 1978.",
    image: "/images/canon-a1.jpg",
    brand: "Canon",
    category: "Cameras",
    price: 349.99,
    countInStock: 4,
    rating: 4.8,
    numReviews: 11,
  },
  {
    id: "6",
    name: "Nikon FM2",
    description:
      "The Nikon FM2 is an advanced semi-professional, interchangeable lens, 35 mm film, single-lens reflex (SLR) camera.",
    image: "/images/nikon-fm2.jpg",
    brand: "Nikon",
    category: "Cameras",
    price: 329.99,
    countInStock: 3,
    rating: 4.9,
    numReviews: 13,
  },
  {
    id: "7",
    name: "Leica M3",
    description:
      "The Leica M3 is a 35 mm rangefinder camera by Ernst Leitz GmbH, introduced in 1954.",
    image: "/images/leica-m3.jpg",
    brand: "Leica",
    category: "Cameras",
    price: 1899.99,
    countInStock: 2,
    rating: 4.7,
    numReviews: 15,
  },
  {
    id: "8",
    name: "Kodak Retina IIa",
    description:
      "The Retina IIa is a 35mm viewfinder camera made by Kodak AG in Germany.",
    image: "/images/kodak-retina-iia.jpg",
    brand: "Kodak",
    category: "Cameras",
    price: 899.99,
    countInStock: 1,
    rating: 4.6,
    numReviews: 7,
  },
  {
    id: "9",
    name: "Polaroid SX-70",
    description:
      "The Polaroid SX-70 is a folding single lens reflex Land camera which was produced by Polaroid Corporation from 1972 to 1981.",
    image: "/images/polaroid-sx70.jpg",
    brand: "Polaroid",
    category: "Cameras",
    price: 499.99,
    countInStock: 5,
    rating: 4.5,
    numReviews: 10,
  },
  {
    id: "10",
    name: "Rolleiflex 2.8F",
    description:
      "The Rolleiflex 2.8F is a twin-lens reflex camera made by Rollei.",
    image: "/images/rolleiflex-28f.jpg",
    brand: "Rolleiflex",
    category: "Cameras",
    price: 1499.99,
    countInStock: 3,
    rating: 4.8,
    numReviews: 14,
  },
  {
    id: "11",
    name: "Zeiss Ikon Contax II",
    description:
      "The Zeiss Ikon Contax II is a 35mm rangefinder camera built by Zeiss Ikon from 1936 to 1942.",
    image: "/images/zeiss-ikon-contax-ii.jpg",
    brand: "Zeiss Ikon",
    category: "Cameras",
    price: 1999.99,
    countInStock: 2,
    rating: 4.9,
    numReviews: 12,
  },
  {
    id: "12",
    name: "Voigtländer Bessa",
    description:
      "The Voigtländer Bessa is a line of medium format and 35mm film cameras manufactured by Voigtländer.",
    image: "/images/voigtlander-bessa.jpg",
    brand: "Voigtländer",
    category: "Cameras",
    price: 799.99,
    countInStock: 4,
    rating: 4.7,
    numReviews: 9,
  },
  {
    id: "13",
    name: "Argus C3",
    description:
      "The Argus C3 is a 35mm film rangefinder camera manufactured by Argus.",
    image: "/images/argus-c3.jpg",
    brand: "Argus",
    category: "Cameras",
    price: 299.99,
    countInStock: 3,
    rating: 4.4,
    numReviews: 8,
  },
  {
    id: "14",
    name: "Konica Auto S3",
    description:
      "The Konica Auto S3 is a 35mm fixed-lens, leaf-shuttered, rangefinder camera.",
    image: "/images/konica-auto-s3.jpg",
    brand: "Konica",
    category: "Cameras",
    price: 379.99,
    countInStock: 6,
    rating: 3.9,
    numReviews: 11,
  },
  {
    id: "15",
    name: "Ansel Adams: 400 Photographs",
    description:
      "A collection of iconic photographs by Ansel Adams, showcasing his mastery of black-and-white landscape photography.",
    image: "/images/ansel-adams-400-photographs.jpg",
    brand: "Ansel Adams",
    category: "Books",
    price: 39.99,
    countInStock: 10,
    rating: 4.1,
    numReviews: 30,
  },
  {
    id: "16",
    name: "Understanding Exposure",
    description:
      "A comprehensive guide to understanding exposure in photography, covering aperture, shutter speed, and ISO.",
    image: "/images/understanding-exposure.jpg",
    brand: "Bryan Peterson",
    category: "Books",
    price: 29.99,
    countInStock: 15,
    rating: 4.7,
    numReviews: 25,
  },
  {
    id: "17",
    name: "The Camera",
    description:
      "A classic photography book exploring the history and technical aspects of the camera.",
    image: "/images/the-camera.jpg",
    brand: "Ansel Adams",
    category: "Books",
    price: 24.99,
    countInStock: 12,
    rating: 4.8,
    numReviews: 20,
  },
  {
    id: "18",
    name: "Magnum Contact Sheets",
    description:
      "A fascinating look at the contact sheets of Magnum photographers, revealing the process behind iconic images.",
    image: "/images/magnum-contact-sheets.jpg",
    brand: "Magnum Photos",
    category: "Books",
    price: 49.99,
    countInStock: 8,
    rating: 4.6,
    numReviews: 18,
  },
  {
    id: "19",
    name: "Camera Shoulder Strap",
    description: "Adjustable vintage leather camera shoulder strap.",
    image: "/images/camera-shoulder-strap.jpg",
    brand: "Vintage Camera Accessories",
    category: "Accessories",
    price: 29.99,
    countInStock: 20,
    rating: 4.5,
    numReviews: 15,
  },
  {
    id: "20",
    name: "Camera Lens Cleaning Kit",
    description:
      "Professional camera lens cleaning kit with lens cleaner, brush, and microfiber cloth.",
    image: "/images/camera-lens-cleaning-kit.jpg",
    brand: "Camera Care Co.",
    category: "Accessories",
    price: 19.99,
    countInStock: 15,
    rating: 4.7,
    numReviews: 12,
  },
  {
    id: "21",
    name: "Camera Tripod",
    description: "Aluminum camera tripod with adjustable legs and ball head.",
    image: "/images/camera-tripod.jpg",
    brand: "SteadyShot",
    category: "Accessories",
    price: 79.99,
    countInStock: 10,
    rating: 4.6,
    numReviews: 18,
  },
  {
    id: "22",
    name: "Camera Bag",
    description:
      "Vintage canvas camera bag with padded interior and adjustable dividers.",
    image: "/images/camera-bag.jpg",
    brand: "RetroGear",
    category: "Accessories",
    price: 49.99,
    countInStock: 25,
    rating: 3.8,
    numReviews: 20,
  },
  {
    id: "23",
    name: "Life Magazine",
    description:
      "An iconic weekly news magazine known for its stunning photojournalism, published from 1936 to 1972.",
    image: "/images/life-magazine.jpg",
    brand: "Time Inc.",
    category: "Magazines",
    price: 19.99,
    countInStock: 10,
    rating: 2.7,
    numReviews: 15,
  },
  {
    id: "24",
    name: "National Geographic Magazine",
    description:
      "A renowned monthly magazine showcasing the world's wonders through captivating photography, founded in 1888.",
    image: "/images/national-geographic-magazine.jpg",
    brand: "National Geographic Society",
    category: "Magazines",
    price: 24.99,
    countInStock: 8,
    rating: 4.8,
    numReviews: 12,
  },
  {
    id: "25",
    name: "Popular Photography",
    description:
      "A popular photography magazine providing tips, techniques, and gear reviews, published from 1937 to 2017.",
    image: "/images/popular-photography-magazine.jpg",
    brand: "Popular Photography",
    category: "Magazines",
    price: 14.99,
    countInStock: 12,
    rating: 4.6,
    numReviews: 10,
  },
  {
    id: "26",
    name: "Vintage Travel Postcards",
    description:
      "A collection of vintage travel postcards featuring scenic destinations from around the world.",
    image: "/images/vintage-travel-postcards.jpg",
    brand: "VTP",
    category: "Postcards",
    price: 9.99,
    countInStock: 20,
    rating: 5,
    numReviews: 18,
  },
  {
    id: "27",
    name: "Vintage Portrait Postcards",
    description:
      "A set of vintage portrait postcards featuring classic portraits from the early 20th century.",
    image: "/images/vintage-portrait-postcards.jpg",
    brand: "VTP",
    category: "Postcards",
    price: 7.99,
    countInStock: 15,
    rating: 4.4,
    numReviews: 14,
  },
  {
    id: "28",
    name: "Vintage City Postcards",
    description:
      "A collection of vintage city postcards showcasing urban scenes from the past century.",
    image: "/images/vintage-city-postcards.jpg",
    brand: "VTP",
    category: "Postcards",
    price: 11.99,
    countInStock: 18,
    rating: 4.6,
    numReviews: 16,
  },
  {
    id: "29",
    name: "Carl Zeiss Jena Biotar 58mm f/2",
    description:
      "A classic vintage lens known for its unique bokeh rendering and sharpness.",
    image: "/images/carl-zeiss-jena-biotar.jpg",
    brand: "Carl Zeiss Jena",
    category: "Lenses",
    price: 499.99,
    countInStock: 5,
    rating: 4.9,
    numReviews: 10,
  },
  {
    id: "30",
    name: "Nikkor-S Auto 50mm f/1.4",
    description:
      "A fast prime lens with excellent low-light performance, ideal for portrait and street photography.",
    image: "/images/nikkor-s-auto-50mm.jpg",
    brand: "Nikon",
    category: "Lenses",
    price: 399.99,
    countInStock: 7,
    rating: 4.8,
    numReviews: 8,
  },
  {
    id: "31",
    name: "Leitz Summicron 50mm f/2",
    description:
      "A legendary lens renowned for its optical quality and craftsmanship, compatible with Leica M-mount cameras.",
    image: "/images/leitz-summicron-50mm.jpg",
    brand: "Leitz",
    category: "Lenses",
    price: 899.99,
    countInStock: 3,
    rating: 4.7,
    numReviews: 6,
  },
  {
    id: "32",
    name: "Canon FL 55mm f/1.2",
    description:
      "A fast standard lens with a wide aperture, suitable for low-light shooting and creating shallow depth of field.",
    image: "/images/canon-fl-55mm.jpg",
    brand: "Canon",
    category: "Lenses",
    price: 599.99,
    countInStock: 4,
    rating: 4.6,
    numReviews: 7,
  },
  {
    id: "33",
    name: "Voigtländer Nokton 35mm f/1.4",
    description:
      "A high-speed lens with excellent image quality and a versatile focal length, compatible with Leica M-mount cameras.",
    image: "/images/voigtlander-nokton-35mm.jpg",
    brand: "Voigtländer",
    category: "Lenses",
    price: 749.99,
    countInStock: 6,
    rating: 4.8,
    numReviews: 9,
  },
  {
    id: "34",
    name: "Minolta Shutter Release Cable",
    description:
      "A vintage shutter release cable designed for Minolta film cameras, allowing remote shutter activation.",
    image: "/images/minolta-shutter-release-cable.jpg",
    brand: "Minolta",
    category: "Parts",
    price: 29.99,
    countInStock: 8,
    rating: 4.3,
    numReviews: 5,
  },
  {
    id: "35",
    name: "Pentax Shutter Release Cable",
    description:
      "A classic shutter release cable compatible with Pentax SLR cameras, providing smooth and precise shutter operation.",
    image: "/images/pentax-shutter-release-cable.jpg",
    brand: "Pentax",
    category: "Parts",
    price: 24.99,
    countInStock: 6,
    rating: 4.2,
    numReviews: 4,
  },
  {
    id: "36",
    name: "Canon Shutter Release Cable",
    description:
      "An original shutter release cable for Canon FD-mount cameras, offering reliable remote shutter control.",
    image: "/images/canon-shutter-release-cable.jpg",
    brand: "Canon",
    category: "Parts",
    price: 34.99,
    countInStock: 10,
    rating: 4.4,
    numReviews: 7,
  },
  {
    id: "37",
    name: "Nikon Hot Shoe Cover",
    description:
      "A vintage hot shoe cover designed for Nikon SLR cameras, protecting the hot shoe from dust and moisture.",
    image: "/images/nikon-hot-shoe-cover.jpg",
    brand: "Nikon",
    category: "Parts",
    price: 9.99,
    countInStock: 20,
    rating: 4.1,
    numReviews: 3,
  },
  {
    id: "38",
    name: "Canon Hot Shoe Cover",
    description:
      "An original hot shoe cover for Canon EOS cameras, preventing dirt and debris from entering the hot shoe.",
    image: "/images/canon-hot-shoe-cover.jpg",
    brand: "Canon",
    category: "Parts",
    price: 7.99,
    countInStock: 18,
    rating: 4.0,
    numReviews: 2,
  },
  {
    id: "39",
    name: "Leica Hot Shoe Cover",
    description:
      "A classic hot shoe cover compatible with Leica M-series cameras, featuring a minimalist design.",
    image: "/images/leica-hot-shoe-cover.jpg",
    brand: "Leica",
    category: "Parts",
    price: 12.99,
    countInStock: 15,
    rating: 4.2,
    numReviews: 4,
  },
  {
    id: "40",
    name: "Leica M Lens Hood",
    description:
      "A vintage metal lens hood designed for Leica M-mount lenses, providing shade and reducing lens flare.",
    image: "/images/leica-m-lens-hood.jpg",
    brand: "Leica",
    category: "Parts",
    price: 49.99,
    countInStock: 15,
    rating: 4.5,
    numReviews: 10,
  },
  {
    id: "41",
    name: "Nikon F Lens Hood",
    description:
      "A classic lens hood compatible with Nikon F-mount lenses, helping to block stray light and protect the lens.",
    image: "/images/nikon-f-lens-hood.jpg",
    brand: "Nikon",
    category: "Parts",
    price: 39.99,
    countInStock: 12,
    rating: 4.6,
    numReviews: 8,
  },
  {
    id: "42",
    name: "Canon FD Lens Hood",
    description:
      "An original lens hood designed for Canon FD-mount lenses, reducing lens flare and improving contrast.",
    image: "/images/canon-fd-lens-hood.jpg",
    brand: "Canon",
    category: "Parts",
    price: 34.99,
    countInStock: 10,
    rating: 4.4,
    numReviews: 6,
  },
] satisfies DummyProduct[]
